"use client";
import { useState } from "react";
import Link from "next/link";
import { useRouter } from "next/navigation";
import { ArrowRight, Check, Eye, EyeOff } from "lucide-react";
import api from "@/lib/api";
import { AuthShell } from "@/components/auth/AuthShell";
export default function SignupPage(){const[name,setName]=useState("");const[email,setEmail]=useState("");const[company,setCompany]=useState("");const[password,setPassword]=useState("");const[visible,setVisible]=useState(false);const[loading,setLoading]=useState(false);const[error,setError]=useState("");const router=useRouter();const checks=[password.length>=12,/[A-Z]/.test(password),/[a-z]/.test(password)&&/[0-9]/.test(password)];async function submit(e:React.FormEvent){e.preventDefault();if(!checks.every(Boolean)){setError("Use at least 12 characters with uppercase, lowercase and a number.");return}setLoading(true);setError("");try{await api.post("/auth/signup",{name,email,company,password});router.push(`/login?created=1`)}catch(err:unknown){setError((err as {response?:{data?:{detail?:string}}}).response?.data?.detail||"We could not create your workspace.")}finally{setLoading(false)}}return <AuthShell eyebrow="Start free" title="Create your workspace" description="No credit card. Connect up to five hosts on the Starter plan."><form className="auth-form" onSubmit={submit}><div className="auth-two"><label>Your name<input required autoComplete="name" value={name} onChange={e=>setName(e.target.value)} placeholder="Alex Morgan"/></label><label>Company<input required autoComplete="organization" value={company} onChange={e=>setCompany(e.target.value)} placeholder="Acme Inc."/></label></div><label>Work email<input required type="email" autoComplete="email" value={email} onChange={e=>setEmail(e.target.value)} placeholder="alex@company.com"/></label><label>Password<div className="auth-password"><input required type={visible?"text":"password"} autoComplete="new-password" value={password} onChange={e=>setPassword(e.target.value)} placeholder="12+ characters"/><button type="button" onClick={()=>setVisible(v=>!v)} aria-label={visible?"Hide password":"Show password"}>{visible?<EyeOff size={16}/>:<Eye size={16}/>}</button></div></label><div className="password-checks"><span className={checks[0]?"ok":""}><Check size={11}/>12+ characters</span><span className={checks[1]?"ok":""}><Check size={11}/>Uppercase</span><span className={checks[2]?"ok":""}><Check size={11}/>Lowercase + number</span></div>{error&&<div className="auth-error">{error}</div>}<button className="auth-submit" disabled={loading} type="submit">{loading?"Creating workspace…":"Create free workspace"}<ArrowRight size={16}/></button><div className="auth-divider"><span>Already have an account?</span></div><Link className="btn btn-secondary auth-alt" href="/login">Sign in</Link></form></AuthShell>}

