"use client";
import Link from "next/link";
import { usePathname, useRouter } from "next/navigation";
import { Bell, ChevronDown, HelpCircle, Search, ShieldCheck } from "lucide-react";
import { useEffect, useRef, useState } from "react";
import api from "@/lib/api";
import { SearchPalette } from "@/components/ui";

const labels:Record<string,string>={"/app":"Overview","/app/dashboards":"Dashboards","/app/servers":"Servers","/app/containers":"Containers","/app/processes":"Processes","/app/network":"Network","/app/storage":"Storage","/app/ports":"Ports","/app/nginx":"Nginx","/app/docker":"Docker","/app/databases":"Databases","/app/redis":"Redis","/app/rabbitmq":"RabbitMQ","/app/alerts":"Alerts","/app/events":"Events","/app/cpu-spikes":"CPU spikes","/app/cron":"Cron jobs","/app/ai":"AI assistant","/app/team":"Team & access","/app/billing":"Plans & billing","/app/audit":"Audit log","/app/settings":"Settings"};
export function Topbar({collapsed=false}:{collapsed?:boolean}){const path=usePathname();const router=useRouter();const[palette,setPalette]=useState(false);const[menu,setMenu]=useState(false);const[alerts,setAlerts]=useState(0);const[user,setUser]=useState<{username?:string;email?:string;role?:string}>({});const ref=useRef<HTMLDivElement>(null);const title=labels[path]||Object.entries(labels).find(([key])=>key!=="/app"&&path.startsWith(key))?.[1]||"Workspace";useEffect(()=>{api.get("/auth/me").then(r=>setUser(r.data)).catch(()=>{try{setUser(JSON.parse(localStorage.getItem("user")||"{}"))}catch{}});api.get("/alerts/summary").then(r=>setAlerts(r.data.active||0)).catch(()=>{});const key=(e:KeyboardEvent)=>{if((e.ctrlKey||e.metaKey)&&e.key.toLowerCase()==="k"){e.preventDefault();setPalette(true)}};const click=(e:MouseEvent)=>{if(ref.current&&!ref.current.contains(e.target as Node))setMenu(false)};window.addEventListener("keydown",key);document.addEventListener("mousedown",click);return()=>{window.removeEventListener("keydown",key);document.removeEventListener("mousedown",click)}},[]);function logout(){localStorage.clear();sessionStorage.clear();router.push("/login")}return <><header className={`v2-topbar ${collapsed?"side-collapsed":""}`}><div className="v2-breadcrumb"><span>Production workspace</span><b>/</b><strong>{title}</strong></div><button className="v2-command" onClick={()=>setPalette(true)}><Search size={15}/><span>Search infrastructure, alerts, events…</span><kbd>⌘ K</kbd></button><div className="v2-top-actions"><span className="v2-readonly"><ShieldCheck size={14}/>Read only</span><Link className="v2-icon-btn" href="/docs" title="Documentation"><HelpCircle size={17}/></Link><Link className="v2-icon-btn" href="/app/alerts" title="Alerts"><Bell size={17}/>{alerts>0&&<i>{alerts>9?"9+":alerts}</i>}</Link><div className="v2-user" ref={ref}><button onClick={()=>setMenu(v=>!v)}><span>{(user.username||"U").slice(0,2).toUpperCase()}</span><div><strong>{user.username||"Workspace user"}</strong><small>{user.role||"viewer"}</small></div><ChevronDown size={13}/></button>{menu&&<div className="v2-user-menu"><div><strong>{user.username||"User"}</strong><span>{user.email||"Signed in"}</span></div><Link href="/app/team">Team & access</Link><Link href="/app/billing">Plans & billing</Link><Link href="/app/settings">Account settings</Link><button onClick={logout}>Sign out</button></div>}</div></div></header>{palette&&<SearchPalette onClose={()=>setPalette(false)}/>}</>}
